logging:
  level:
    org:
      hibernate:
        type: trace
spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/gifts
      maximum-pool-size: 15
      password: admin
      username: root
    password: admin
    url: jdbc:mysql://localhost:3306/gifts
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        enable_lazy_load_no_trans: true
      org:
        hibernate:
          envers:
            store_data_at_delete: true
    show-sql: true
